# Change these first
owner: greencent # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API
    url: https://api.greencent.io
    expectedStatusCodes:
      - 200
      - 401
  - name: Auth
    url: https://auth.greencent.io
  - name: Website
    url: https://greencent.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: status.greencent.io
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "[Greencent.io](https://greencent.io) status"
  navbar:
    - title: Status
      href: /
  favicon: https://greencent.io/wp-content/themes/bootscore-main/img/favicon/favicon-32x32.png

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
